### ISSUE TITLE
Re-sync functionality 

### ISSUE THREAD

**Issue by smecham** [freeezer98/export-archive-reddit-saved#4]
Hey there - noob question here but does this script contain an automatic resyncing functionality or do you have to manually run the python file every time you want to update the html? Not seeing some of my newer saves and am wondering if it's because I have to rerun the script. 

Thanks in advance!

**Comment by nooneswarup** [comment]
You need to run the script each time you want to update the HTML. 

I'll update the script when I'm free, with more functionality. (I noticed it's possible to retrieve more than 1000 saved using pushshift API)
